import type { NextPage } from "next";
import Head from "next/head";
import { HomeEarnigs, HomeHead, HomeGuide } from "../components";
import { BasicLayout } from "../components/layouts";

const guideMock: {
  [key: number]: {
    guideId: number;
    guideIdeogram: string;
    description: string;
  };
} = {
  1: {
    guideId: 1,
    guideIdeogram: "🖥",
    description: "あああああああああああああああああああああああああああ",
  },
  2: {
    guideId: 2,
    guideIdeogram: "🖥",
    description: "あああああああああああああああああああああああああああ",
  },
  3: {
    guideId: 3,
    guideIdeogram: "🖥",
    description: "あああああああああああああああああああああああああああ",
  },
  4: {
    guideId: 4,
    guideIdeogram: "🖥",
    description: "あああああああああああああああああああああああああああ",
  },
  5: {
    guideId: 5,
    guideIdeogram: "🖥",
    description: "あああああああああああああああああああああああああああ",
  },
  6: {
    guideId: 6,
    guideIdeogram: "🖥",
    description: "あああああああああああああああああああああああああああ",
  },
  7: {
    guideId: 7,
    guideIdeogram: "🖥",
    description: "あああああああああああああああああああああああああああ",
  },
};

const Home: NextPage = () => {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout type="home">
        <HomeHead
          orderUrl="https://food-web-alpha.vercel.app/menu"
          siteUrl="https://food-web-alpha.vercel.app/"
          storeName="コンピュータ研究部"
        />
        <HomeEarnigs
          totalEarnings={361280}
          totalOrders={962}
          earningsUrl="https://food-web-alpha.vercel.app/sales"
        />
        <HomeGuide guides={Object.values(guideMock)} />
      </BasicLayout>
    </div>
  );
};

export default Home;
