import type { NextPage } from "next";
import Head from "next/head";

import { Layout } from "../components";

const Home: NextPage = () => {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="ml-5p w-23p h-full">
        <Layout chosen="home" />
      </div>
    </div>
  );
};

export default Home;
